---
- name: Update LogicPlum MCRSM repository and run docker-compose (Production)
  hosts: localhost
  connection: local
  become: true
  gather_facts: no
  vars:
    repo_url: "git@github.com:LogicPlum/MCRSM.git"
    repo_dest: "/home/lpreifind/marketCrashRiskSignalModel/core/MCRSM"
    branch: "main"  # Branch name
    docker_compose_file_path: "/home/lpreifind/marketCrashRiskSignalModel/core/MCRSM/docker-compose-prod.yml"
  tasks:
    - name: Pull the latest changes from the MCRSM repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ branch }}"

    - name: Build Docker containers
      command: docker-compose -f "{{ docker_compose_file_path }}" build --no-cache
      args:
        chdir: "{{ repo_dest }}"

    - name: Stop Docker containers
      command: docker-compose -f "{{ docker_compose_file_path }}" down
      args:
        chdir: "{{ repo_dest }}"

    - name: Wait for 5 seconds
      pause:
        seconds: 5

    - name: Start Docker containers
      command: docker-compose -f "{{ docker_compose_file_path }}" up -d
      args:
        chdir: "{{ repo_dest }}"

